In [23]:
import pandas as pd
import numpy as np

In [24]:
df = pd.read_excel('resumo_media_desvio.xlsx')

mean_col = [col for col in df.columns if 'mean' in col]

df = df[df['dataset'] == 'adult']

In [25]:
mean_col = [col for col in df.columns if 'mean' in col]

mean_col

['acc_mean', 'rec_mean', 'prec_mean', 'f1_mean', 'ddp_mean', 'deo_mean']

In [ ]:
baseline_values = df.loc[df['solution_type'] == 'baseline', mean_col].values

df_diff = np.abs(baseline_values - df[mean_col])

margem = df_diff[['acc_mean', 'rec_mean', 'prec_mean','f1_mean']].sum(axis=1) - df_diff[['ddp_mean','deo_mean']].sum(axis=1)

np.argsort(margem)

TypeError: absolute() got an unexpected keyword argument 'axis'

In [35]:
np.abs(baseline_values - df[mean_col])

    acc_mean  rec_mean  prec_mean   f1_mean  ddp_mean  deo_mean
0   0.000000  0.000000   0.000000  0.000000  0.000000  0.000000
1   0.107165  0.330748   0.132427  0.339517  0.136602  0.056211
2   0.043882  0.363638   0.180699  0.295920  0.119032  0.049583
3   0.036947  0.184446   0.082986  0.160966  0.066518  0.033435
4   0.012564  0.143011   0.073501  0.093546  0.051242  0.023468
5   0.044881  0.372657   0.184983  0.301456  0.122366  0.051853
6   0.017325  0.176676   0.089560  0.124173  0.061756  0.028129
7   0.004599  0.103658   0.057132  0.050453  0.040406  0.015998
8   0.004353  0.100955   0.055777  0.048761  0.039361  0.014837
9   0.003193  0.075988   0.041191  0.036152  0.029875  0.013023
10  0.003420  0.081121   0.044182  0.038703  0.031774  0.013063
11  0.004354  0.100981   0.055796  0.048776  0.039378  0.014816
12  0.003433  0.082617   0.045182  0.039329  0.032460  0.013865

In [33]:
np.abs(df_diff[['acc_mean', 'rec_mean', 'prec_mean','f1_mean']].sum(axis=1))

0     0.000000
1     0.645002
2     0.522741
3     0.299372
4     0.175619
5     0.534010
6     0.228613
7     0.101579
8     0.098291
9     0.074142
10    0.079062
11    0.098316
12    0.080197
dtype: float64

In [30]:
df

,dataset,selector,objective,solution_type,acc_mean,acc_std,rec_mean,rec_std,prec_mean,prec_std,f1_mean,f1_std,ddp_mean,ddp_std,deo_mean,deo_std
0,adult,topsis,ddp,baseline,0.848686,0.000000,0.602670,0.000000,0.738668,0.000000,0.663775,0.000000,0.173294,0.000000,0.058001,0.000000
1,adult,topsis,ddp,post,0.741521,0.168953,0.271923,0.250842,0.871095,0.213565,0.324258,0.047351,0.036692,0.014367,0.001790,0.001586
2,adult,topsis,ddp + deo,post,0.804804,0.017000,0.239032,0.097120,0.919367,0.043509,0.367855,0.105661,0.054263,0.027189,0.008418,0.011751
3,adult,topsis,ddp_kl,post,0.811740,0.063922,0.418224,0.211131,0.821654,0.135878,0.502809,0.139366,0.106777,0.059304,0.024566,0.021446
4,adult,topsis,ddp_kl + deo_kl,post,0.836123,0.015244,0.459660,0.126679,0.812169,0.064371,0.570229,0.100521,0.122052,0.042007,0.034533,0.016738
5,adult,topsis,deo,post,0.803805,0.012942,0.230013,0.069168,0.923651,0.029796,0.362319,0.080197,0.050928,0.018488,0.006149,0.008108
6,adult,topsis,deo_kl,post,0.831361,0.019164,0.425995,0.146478,0.828228,0.072601,0.539602,0.123803,0.111538,0.047270,0.029872,0.019674
7,adult,zenith,ddp,post,0.844087,0.000787,0.499012,0.008523,0.795800,0.004359,0.613321,0.005357,0.132888,0.003395,0.042004,0.003517
8,adult,zenith,ddp + deo,post,0.844334,0.000275,0.501716,0.003241,0.794445,0.001892,0.615014,0.001928,0.133933,0.001320,0.043164,0.001158
9,adult,zenith,ddp_kl,post,0.845493,0.001557,0.526682,0.033370,0.779859,0.019543,0.627623,0.016869,0.143419,0.012716,0.044979,0.003117
10,adult,zenith,ddp_kl + deo_kl,post,0.845267,0.001420,0.521549,0.030928,0.782850,0.017981,0.625071,0.015496,0.141520,0.011801,0.044938,0.003102
11,adult,zenith,deo,post,0.844332,0.000263,0.501689,0.003364,0.794464,0.002078,0.614998,0.001964,0.133916,0.001418,0.043186,0.001335
12,adult,zenith,deo_kl,post,0.845253,0.001370,0.520053,0.028593,0.783850,0.016698,0.624445,0.014542,0.140835,0.010815,0.044137,0.002606